import type { Metadata } from "next";
import Link from "next/link";
import { canonicalUrl } from "@/lib/site";
import { LegalPageShell } from "@/components/legal/LegalPageShell";
import { SUBPROCESSORS } from "@/lib/subprocessors";

export const metadata: Metadata = {
  title: "Data Processing Agreement | Zoveto",
  description:
    "Review Zoveto's Data Processing Agreement covering DPDP Act 2023 alignment, processing purposes, data categories, subprocessors, security, audit, export, and deletion.",
  alternates: { canonical: canonicalUrl("/dpa") },
  robots: { index: true, follow: true },
};

const PROCESSING_PURPOSES = [
  {
    purpose: "Service delivery",
    description: "Hosting, operating, maintaining, and improving the subscribed Zoveto services.",
  },
  {
    purpose: "Account administration",
    description:
      "Creating accounts, managing users, roles, permissions, authentication, and billing administration.",
  },
  {
    purpose: "Customer support",
    description: "Troubleshooting, diagnostics, issue resolution, and support communications.",
  },
  {
    purpose: "Implementation and migration",
    description:
      "Onboarding, configuration, data import, workflow setup, training, and professional services where agreed.",
  },
  {
    purpose: "Security and abuse prevention",
    description:
      "Monitoring, logging, fraud prevention, incident detection, access control, and protection of systems and data.",
  },
  {
    purpose: "Analytics and product improvement",
    description:
      "Aggregated or usage-based analysis to improve reliability, performance, usability, and product functionality.",
  },
  {
    purpose: "Legal and compliance",
    description:
      "Maintaining records required for tax, accounting, contractual, regulatory, security, and legal obligations.",
  },
  {
    purpose: "Communications",
    description:
      "Service notices, administrative messages, product updates, and customer-success communications related to the services.",
  },
] as const;

const PERSONAL_DATA_CATEGORIES = [
  {
    category: "Account and user data",
    examples: "Names, work emails, phone numbers, organisation names, job titles, user IDs, roles, and permissions.",
  },
  {
    category: "Authentication and access data",
    examples:
      "Login metadata, access timestamps, IP addresses, session information, device/browser information, and security logs.",
  },
  {
    category: "Business operations data",
    examples:
      "Inventory, warehouse, procurement, sales/CRM, finance/GST, HR, MRO, vendor, customer, and workflow records uploaded or generated by Customer.",
  },
  {
    category: "Support data",
    examples:
      "Support tickets, messages, diagnostics, screenshots, files, call notes, and troubleshooting information shared by Customer.",
  },
  {
    category: "Billing and commercial data",
    examples: "Billing contacts, invoices, subscription plan, payment status, GST/tax details, and order-form information.",
  },
  {
    category: "Usage and telemetry data",
    examples: "Product usage events, feature interactions, performance logs, error logs, and analytics data.",
  },
  {
    category: "Communications data",
    examples:
      "Service emails, administrative messages, demo or onboarding communications, and customer-success interactions.",
  },
] as const;

const tableClass = "w-full min-w-[680px] border-collapse text-left";
const thClass = "border-b border-border px-4 py-3 text-sm font-semibold text-foreground";
const tdClass = "border-b border-border px-4 py-3 text-sm text-muted";

export default function DpaPage() {
  return (
    <LegalPageShell
      title="Data Processing Agreement"
      lastUpdated="April 2026"
      pdfHref="/legal/zoveto-data-processing-agreement-april-2026.pdf"
    >
      <section>
        <p className="rounded-lg border border-border bg-card p-4 font-medium text-foreground">
          This Data Processing Agreement applies when Zoveto processes Customer personal data on behalf of a Customer under
          an order form, subscription, pilot, statement of work, enterprise agreement, or other written agreement that
          references this DPA.
        </p>
        <p className="mt-4">
          This DPA forms part of the applicable agreement between{" "}
          <strong>Zoveto Technologies Private Limited</strong> (&ldquo;Zoveto&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) and
          the customer identified in the applicable order form or written agreement (&ldquo;Customer&rdquo;,
          &ldquo;you&rdquo;).
        </p>
      </section>

      <section>
        <h2>Agreement and scope</h2>
        <p>
          This Data Processing Agreement (&ldquo;DPA&rdquo;) governs Zoveto&apos;s processing of Customer personal data in
          connection with the subscribed services, including pilots, implementation services, and related support described in
          the applicable agreement, order form, or statement of work.
        </p>
        <p>
          This DPA applies to personal data processed by Zoveto on behalf of Customer through the Zoveto platform and related
          services. It does not apply to personal data for which Zoveto acts as an independent Data Fiduciary, such as
          website visitor data processed under Zoveto&apos;s own{" "}
          <Link href="/privacy">Privacy Policy</Link>, except where expressly stated.
        </p>
      </section>

      <section>
        <h2>Roles of the parties</h2>
        <p>Unless otherwise agreed in writing:</p>
        <ul>
          <li>Customer determines the purposes and means of processing Customer personal data.</li>
          <li>Customer acts as Data Fiduciary/controller where applicable.</li>
          <li>
            Zoveto acts as Data Processor/service provider where it processes Customer personal data on Customer&apos;s
            instructions.
          </li>
          <li>Each party remains responsible for its own compliance obligations under applicable law.</li>
        </ul>
      </section>

      <section>
        <h2>DPDP Act 2023 alignment</h2>
        <p>
          Zoveto will process personal data in accordance with applicable data protection law, including India&apos;s Digital
          Personal Data Protection Act, 2023 where applicable.
        </p>
        <p>
          Zoveto processes Customer personal data only on documented Customer instructions, including the agreement, order
          form, product configuration, support requests, and written instructions.
        </p>
        <p>
          Zoveto will reasonably assist Customer with Data Principal rights, grievance, consent withdrawal, correction,
          deletion, nomination, security, breach response, and deletion/return obligations where applicable.
        </p>
        <p>
          Zoveto will ensure authorised personnel are bound by confidentiality obligations.
        </p>
        <p>Zoveto will not sell Customer personal data.</p>
        <p>
          Zoveto will not process Customer personal data for unrelated advertising or unrelated profiling.
        </p>
      </section>

      <section>
        <h2>Processing purposes</h2>
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className={tableClass}>
            <thead>
              <tr className="bg-muted/30">
                <th className={thClass}>Purpose</th>
                <th className={thClass}>Description</th>
              </tr>
            </thead>
            <tbody>
              {PROCESSING_PURPOSES.map((row) => (
                <tr key={row.purpose} className="align-top">
                  <td className={`${tdClass} font-medium text-foreground`}>{row.purpose}</td>
                  <td className={tdClass}>{row.description}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>Categories of personal data</h2>
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className={tableClass}>
            <thead>
              <tr className="bg-muted/30">
                <th className={thClass}>Category</th>
                <th className={thClass}>Examples</th>
              </tr>
            </thead>
            <tbody>
              {PERSONAL_DATA_CATEGORIES.map((row) => (
                <tr key={row.category} className="align-top">
                  <td className={`${tdClass} font-medium text-foreground`}>{row.category}</td>
                  <td className={tdClass}>{row.examples}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>Categories of Data Principals</h2>
        <ul>
          <li>Customer employees, workers, contractors, and authorised users.</li>
          <li>Customer&apos;s vendors, suppliers, distributors, and logistics partners.</li>
          <li>Customer&apos;s customers, leads, prospects, and business contacts.</li>
          <li>
            Customer&apos;s finance, accounting, procurement, warehouse, operations, sales, HR, and management users.
          </li>
          <li>Other individuals whose personal data is submitted to the services by or on behalf of Customer.</li>
        </ul>
      </section>

      <section>
        <h2>Customer instructions</h2>
        <p>
          Zoveto will process Customer personal data only according to documented Customer instructions.
        </p>
        <p>
          Customer is responsible for ensuring it has the rights, notices, consents, authorisations, and lawful basis needed
          to submit Customer personal data to the services.
        </p>
        <p>
          Zoveto may decline or suspend processing instructions that are unlawful, unsafe, technically infeasible, or outside
          the subscribed services.
        </p>
        <p>
          Zoveto will inform Customer if Zoveto believes an instruction infringes applicable data protection law.
        </p>
      </section>

      <section>
        <h2>Confidentiality</h2>
        <p>
          Zoveto shall ensure that personnel authorized to process Customer personal data are subject to confidentiality
          obligations that survive termination of their employment or engagement.
        </p>
      </section>

      <section>
        <h2>Security measures</h2>
        <p>Zoveto maintains reasonable organisational and technical measures suitable for SaaS operations, including:</p>
        <ul>
          <li>access controls and least-privilege access for personnel and systems;</li>
          <li>encryption in transit (TLS) and encryption at rest for core production systems;</li>
          <li>backup and recovery measures aligned to service reliability needs;</li>
          <li>logging and monitoring for operational and security events;</li>
          <li>administrative safeguards for change management, credential handling, and internal access.</li>
        </ul>
        <p>
          Further security details are described on the <Link href="/security">Security &amp; Data Protection</Link> page.
        </p>
      </section>

      <section>
        <h2>Business continuity and disaster recovery</h2>
        <p>
          Zoveto shall maintain commercially reasonable business continuity, backup, and disaster recovery measures
          appropriate to the nature of the Services and associated operational risks.
        </p>
      </section>

      <section>
        <h2>Security testing</h2>
        <p>
          Zoveto may conduct vulnerability assessments, penetration testing, security reviews, and continuous monitoring
          activities to maintain the security, availability, and integrity of the Services.
        </p>
      </section>

      <section>
        <h2>Security incidents</h2>
        <p>
          Zoveto will notify Customer without undue delay after confirming a security incident affecting Customer personal
          data.
        </p>
        <p>
          Notification will include available information about the nature of the incident, affected data, likely impact,
          mitigation steps, and recommended customer actions where available.
        </p>
        <p>
          Zoveto will take reasonable steps to investigate, contain, remediate, and reduce recurrence of confirmed incidents.
        </p>
        <p>
          Customer is responsible for regulatory or Data Principal notifications where Customer is the Data
          Fiduciary/controller unless otherwise required by law or agreed in writing.
        </p>
      </section>

      <section>
        <h2>Subprocessors</h2>
        <p>
          Zoveto may use subprocessors to provide hosting, infrastructure, analytics, communications, support, security, and
          operational services.
        </p>
        <p>
          The current subprocessor list is incorporated into this DPA by reference and is available at{" "}
          <Link href="/subprocessors">/subprocessors</Link>.
        </p>
        <p>
          Zoveto remains responsible for subprocessors&apos; performance of data protection obligations to the extent
          required by applicable law and contract. Zoveto will impose appropriate confidentiality and data protection
          obligations on subprocessors.
        </p>
        <p className="mt-4 font-medium text-foreground">Current subprocessors (summary)</p>
        <div className="mt-2 overflow-x-auto rounded-lg border border-border">
          <table className={tableClass}>
            <thead>
              <tr className="bg-muted/30">
                <th className={thClass}>Provider</th>
                <th className={thClass}>Purpose</th>
              </tr>
            </thead>
            <tbody>
              {SUBPROCESSORS.map((item) => (
                <tr key={item.provider} className="align-top">
                  <td className={`${tdClass} font-medium text-foreground`}>{item.provider}</td>
                  <td className={tdClass}>{item.purpose}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>Subprocessor changes</h2>
        <p>
          Zoveto may update its list of subprocessors from time to time and shall provide reasonable notice of material
          subprocessor additions through its subprocessor page or other commercially reasonable means.
        </p>
      </section>

      <section>
        <h2>Government and regulatory requests</h2>
        <p>
          Unless prohibited by applicable law, Zoveto shall promptly notify Customer of any legally binding request from a
          governmental authority, regulator, court, or law enforcement agency seeking access to Customer personal data and
          shall reasonably cooperate with Customer regarding such request.
        </p>
      </section>

      <section>
        <h2>Data minimization</h2>
        <p>
          Zoveto shall process only the personal data reasonably necessary to provide the Services, comply with Customer
          instructions, satisfy legal obligations, and maintain service security and reliability.
        </p>
      </section>

      <section>
        <h2>Commercial use restriction</h2>
        <p>
          Zoveto will not sell, rent, disclose for monetary consideration, or commercially exploit Customer personal data
          except as necessary to provide the Services or as required by applicable law.
        </p>
      </section>

      <section>
        <h2>Data export</h2>
        <p>
          During the subscription term and any applicable post-termination export period, Customer may request export of
          Customer personal data in a commercially reasonable electronic format where technically available.
        </p>
      </section>

      <section>
        <h2>Return and deletion after contract end</h2>
        <p>
          On expiry or termination of the applicable agreement, Customer may request export or return of Customer personal
          data where technically available under the subscribed plan or order form.
        </p>
        <p>
          Unless a longer period is required by law, tax, accounting, dispute, security, backup, or legitimate business
          requirements, Zoveto will delete or anonymise Customer personal data from active production systems within{" "}
          <strong>sixty (60) days</strong> after contract end or written deletion request.
        </p>
        <p>
          Residual backup copies may remain in encrypted or access-controlled backups for up to{" "}
          <strong>ninety (90) days</strong> and will be deleted or overwritten in the ordinary backup lifecycle.
        </p>
        <p>
          Zoveto may retain limited records required for legal, tax, accounting, fraud prevention, security, dispute
          resolution, or contract enforcement purposes.
        </p>
        <p>
          Deleted or anonymised data will not be restored to production systems except where required for legal, security, or
          disaster recovery purposes.
        </p>
      </section>

      <section>
        <h2>Data Principal requests</h2>
        <p>
          Customer is responsible for responding to Data Principal requests where Customer is the Data Fiduciary/controller.
        </p>
        <p>
          Zoveto will reasonably assist Customer with access, correction, deletion, grievance, consent withdrawal, and
          nomination-related requests to the extent such requests relate to Customer personal data processed by Zoveto.
        </p>
        <p>
          Zoveto may redirect a Data Principal request to Customer where the request relates to Customer-controlled data.
        </p>
      </section>

      <section>
        <h2>Audit and compliance verification</h2>
        <p>
          Upon reasonable written request and not more than once in any twelve-month period, Zoveto shall provide Customer
          with information reasonably necessary to demonstrate compliance with this DPA, including available security
          documentation, policies, certifications, or audit reports where applicable. Any audit activities shall be subject
          to reasonable confidentiality, security, operational, and scheduling requirements.
        </p>
      </section>

      <section>
        <h2>Data residency and cross-border processing</h2>
        <p>
          Where personal data is transferred across borders, Zoveto applies contractual and technical safeguards required by
          applicable law.
        </p>
        <p>
          For production customer data where Zoveto has committed India-only data residency in the applicable order form or
          security documentation, Zoveto will host such production data in India, subject to approved subprocessors and lawful
          processing requirements.
        </p>
        <p>
          Some metadata, support, analytics, email, payment, or communication workflows may be processed by approved
          subprocessors outside India as described on the <Link href="/subprocessors">Subprocessors</Link> page and{" "}
          <Link href="/security">Security</Link> page.
        </p>
      </section>

      <section>
        <h2>Conflict with main agreement</h2>
        <p>
          If there is a conflict between this DPA and the main agreement, this DPA controls only for data protection and
          processing of Customer personal data.
        </p>
        <p>
          Commercial terms remain governed by the main agreement, order form, or{" "}
          <Link href="/msa">Master Service Agreement (MSA)</Link>.
        </p>
      </section>

      <section>
        <h2>Term</h2>
        <p>
          This DPA remains in effect for as long as Zoveto processes Customer personal data on behalf of Customer.
        </p>
        <p>
          Sections intended to survive termination continue as necessary, including confidentiality, deletion/return, audit
          records, liability, and legal compliance.
        </p>
      </section>

      <section>
        <h2>Related policies</h2>
        <ul>
          <li>
            <Link href="/privacy">Privacy Policy</Link>
          </li>
          <li>
            <Link href="/terms">Terms of Service</Link>
          </li>
          <li>
            <Link href="/msa">Master Service Agreement (MSA)</Link>
          </li>
          <li>
            <Link href="/security">Security &amp; Data Protection</Link>
          </li>
          <li>
            <Link href="/subprocessors">Subprocessors</Link>
          </li>
        </ul>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          DPA and enterprise privacy requests: <a href="mailto:privacy@zoveto.com">privacy@zoveto.com</a>
        </p>
        <p>
          Grievance officer details for Data Principal complaints are available in the{" "}
          <Link href="/privacy#grievance">Privacy Policy</Link>.
        </p>
      </section>
    </LegalPageShell>
  );
}
