import { createBlogPost } from "../actions";

export default function NewBlogPostPage() {
  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold tracking-tight text-zinc-100 mb-8">Create Raw Blog Post</h1>
      
      <form action={createBlogPost} className="space-y-6 bg-black p-8 rounded-2xl border border-zinc-800 shadow-xl">
        <div className="grid grid-cols-2 gap-6">
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-500 mb-2">Author</label>
            <input name="author" required defaultValue="Zoveto" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm text-zinc-200 outline-none focus:border-zinc-600" />
          </div>
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-500 mb-2">Cover Image URL (Cloudinary)</label>
            <input name="coverImage" type="url" className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm text-zinc-200 outline-none focus:border-zinc-600 placeholder-zinc-700" placeholder="https://res.cloudinary.com/..." />
          </div>
        </div>

        <div>
          <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-500 mb-2">Raw Content (HTML/Markdown)</label>
          <textarea name="content" required rows={20} className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm text-zinc-200 outline-none focus:border-zinc-600 font-mono leading-relaxed" placeholder="<h1>Paste raw HTML or Markdown here...</h1>&#10;&#10;Title, slug, and excerpt will be auto-generated by the backend!" />
        </div>

        <div className="flex items-center gap-2">
          <input type="checkbox" name="published" value="true" id="published" className="h-4 w-4 rounded border-zinc-800 bg-zinc-950 text-zinc-100" />
          <label htmlFor="published" className="text-sm font-medium text-zinc-300">Publish immediately</label>
        </div>

        <button type="submit" className="w-full rounded-xl bg-zinc-100 px-4 py-3 text-sm font-semibold text-zinc-900 transition-all hover:bg-white hover:shadow-lg active:scale-[0.99]">
          Save & Publish Post
        </button>
      </form>
    </div>
  );
}
